### ISSUE TITLE
declare grep dependency / or replace with busybox only solution

### ISSUE THREAD

**Issue by ray0711** [mueslo/openwrt_hass_devicetracker#2]
The inbuilt busybox grep doesn't support the -P option.
Running sync_state gives errors that P is not supported and doesn't send the hostnames to home-assistant.
Installing the full grep package solves it. 

Alternative without additional dependencies:
```bash
function get_host_name {
    # get hostname for mac
    x=$(nslookup "$(get_ip $1)" | grep -o "name = .*$")
   hostname=${x:6}
    ...
```

**Comment by torarnv** [comment]
Hit this too, the fix in comment by @ray0711 works

**Comment by torarnv** [comment]
Actually, the fix above doesn't work as it doesn't print x. Here's a working version:
```
function get_host_name {
    # get hostname for mac
    nslookup "$(get_ip $1)" | grep -o "name = .*$" | cut -d ' ' -f 3
}
```

**Comment by mueslo** [comment]
I've declared the grep dependency for the time being (16c6685a50b45ac77b0443dcbc362bcca3f1448d) since https://github.com/mueslo/openwrt_hass_devicetracker/blob/master/packages/net/hass/files/hassd.sh#L22 contains a lookahead expression. The output it listens to looks like

```
{ "ubus.object.add": {"id":-1078576401,"path":"hostapd.wlan0"} }
{ "ubus.object.add": {"id":113349837,"path":"hostapd.wlan0"} }
{ "ubus.object.add": {"id":-1049996691,"path":"hostapd.wlan0-1"} }
```

So if you want to write a busybox-compatible version that extracts the interface names from that output, feel free to submit a pull request.

**Comment by zxdavb** [comment]
I had to use busybox grep because it is indirectly obligated by LXC. 

@torarnv 's proposed solution, `grep -o "name = .*$" | cut -d ' ' -f 3` worked for me.

**Comment by mueslo** [comment]
Just figured out how to explicitly run busybox grep: `busybox grep`

I'll implement it soon.

**Comment by mueslo** [comment]
resolved in https://github.com/mueslo/openwrt_hass_devicetracker/commit/28e0da835336f5f04434c7e8bea95edcc819aec0
